// <auto-generated />
namespace PequenoProdutor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class quartaMigracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quartaMigracao));
        
        string IMigrationMetadata.Id
        {
            get { return "202103140347348_quartaMigracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
